### ISSUE TITLE
Sequence Diagram Lab

### ISSUE THREAD

**Issue by jxwn** [comp129/comp55#57]
For this lab, students are meant to play around with PlantUML in order to create their sequence diagram. I propose adding a link to a short video at the bottom of the page in case students don't quite understand how creating diagrams work. In the video, it explains the basics of the elements as well as the interactions these elements can have with each other depending on how you connect them. 
video : https://www.youtube.com/watch?v=KzBlSvFxF7U

**Comment by jlam39** [comment]
Would it be possible for me to add a couple of screenshots or gifs of just a select few examples that can be used in the "Fancy Options" portion? I remember things that I wanted to do such as text alignment and adding a delay to the diagram, but having issues doing so since I may or may not have just skimmed the syntax options that you provided. Having it show some of the "important" ones might help students create their documents.
