### ISSUE TITLE
Update Debug Lab

### ISSUE THREAD

**Issue by Kobyizunaso** [comp129/comp55#99]
Debugging lab is well organized but lacks so more details. For example, there are other ways to add a breakpoint in eclipse not mentioned. I would like to add more concrete text and images to improve the context of debugging lab. I would also like to add more tips to debugging as coming into it as a first timer can be overwhelming without prior advice and knowledge. Adding more tips and links to other articles on how to approach debugging could help.

**Comment by onzfonz** [comment]
normally you would want more of a description here that describes more of the problem/issue so that it is clearer what would be fixed.  Based on the time limitation I will let you move forward, but please keep that in mind.  Feel free to look at other issues to see the larger amount of description that they have.

I think it's good to provide more specificity here.
